name: jupyterdask
channels:
 - conda-forge
dependencies:
  - python=3.11
  - bokeh=3.2.2  # https://github.com/dask/dask-labextension/issues/270
  - dask-jobqueue
  - dask-labextension
  - dask[complete]  
  - jupyterlab

